### ISSUE TITLE
"Unexplored" label is always added

### ISSUE THREAD

**Issue by volkm** [moves-rwth/storm#559]
The "unexplored" label introduced in #521 seems to be added even if all states are explored.

For the command
```
./bin/storm --prism ../resources/examples/testfiles/dtmc/die.pm
```
the resulting model still has the "unexplored" label:
```
--------------------------------------------------------------
Model type: 	DTMC (sparse)
States: 	13
Transitions: 	20
Reward Models:  none
State Labels: 	3 labels
   * unexplored -> 0 item(s)
   * deadlock -> 0 item(s)
   * init -> 1 item(s)
Choice Labels: 	none
--------------------------------------------------------------
```

Or is the "unexplored" label supposed to always be present (like "init" and "deadlock")?

**Comment by tquatmann** [comment]
Thanks! This was indeed an oversight. I don't think the `unexplored` label should be present all the time.
Fixed in #560

**Comment by volkm** [comment]
It is not completely fixed yet:
`./bin/storm --prism ../resources/examples/testfiles/dtmc/die.pm --prop "P=? [F \"one\"]"`
still has the unexplored label present for the goal state
```
--------------------------------------------------------------
Model type: 	DTMC (sparse)
States: 	13
Transitions: 	20
Reward Models:  none
State Labels: 	4 labels
   * unexplored -> 1 item(s)
   * deadlock -> 0 item(s)
   * init -> 1 item(s)
   * one -> 1 item(s)
Choice Labels: 	none
--------------------------------------------------------------
```
